sudo: false
language: go
go:
  - 1.5
  - 1.6
  - tip

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install:
  - go get -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -repotoken ODVVqrmKEbXYriRSKushcupIC0UUwjBxv
